const itens = [
  ...[
    ['ARTICULAÇÕES FIBROSAS','Sutura Coronal'],['ARTICULAÇÕES FIBROSAS','Sutura Sagital'],['ARTICULAÇÕES FIBROSAS','Membrana Interóssea radio-ulnar - sindesmose'],['ARTICULAÇÕES FIBROSAS','Membrana Interóssea tibiofibular - sindesmose'],['ARTICULAÇÕES FIBROSAS','Articulação Alvéolo Dentário - Gonfose'],
    ['ARTICULAÇÕES CARTILAGÍNEAS','Articulação Esterno Costal - Sincondrose'],['ARTICULAÇÕES CARTILAGÍNEAS','Sínfise Púbica'],['ARTICULAÇÕES CARTILAGÍNEAS','Anel Fibroso do Disco Intervertebral - sínfise'],['ARTICULAÇÕES CARTILAGÍNEAS','Núcleo Pulposo do Disco Intervertebral'],
    ['ARTICULAÇÕES SINOVIAIS','Cartilagem Articular'],['ARTICULAÇÕES SINOVIAIS','Ligamento Colateral Tibial'],['ARTICULAÇÕES SINOVIAIS','Ligamento Colateral Fibular'],['ARTICULAÇÕES SINOVIAIS','Menisco Lateral'],['ARTICULAÇÕES SINOVIAIS','Menisco Medial'],['ARTICULAÇÕES SINOVIAIS','Ligamento Cruzado Anterior'],['ARTICULAÇÕES SINOVIAIS','Ligamento Cruzado Posterior'],['ARTICULAÇÕES SINOVIAIS','Lábio Acetabular'],['ARTICULAÇÕES SINOVIAIS','Cápsula Articular - Articulação do Quadril'],['ARTICULAÇÕES SINOVIAIS','Lábio Glenoidal'],['ARTICULAÇÕES SINOVIAIS','Cápsula Articular - Articulação do Ombro']
  ].map((x,i)=>({id:'art-'+(i+1),roteiro:'Articulações',grupo:x[0],numero:i+1,nome:x[1]})),
  ...[
    ['Membro superior - ombro','m. deltóide'],['Membro superior - ombro','m. supraespinhal'],['Membro superior - ombro','m. infraespinal'],['Membro superior - ombro','m. redondo menor'],['Membro superior - ombro','m. redondo maior'],['Membro superior - ombro','m. subescapular'],
    ['Membro superior - braço','m. bíceps braquial'],['Membro superior - braço','m. braquial'],['Membro superior - braço','m. coracobraquial'],['Membro superior - braço','m. tríceps braquial'],
    ['Membro superior - antebraço','m. ancôneo'],['Membro superior - antebraço','m. extensor ulnar do carpo'],['Membro superior - antebraço','m. extensor dos dedos'],['Membro superior - antebraço','m. extensor do dedo mínimo'],['Membro superior - antebraço','m. abdutor longo do polegar'],['Membro superior - antebraço','m. extensor curto do polegar'],['Membro superior - antebraço','m. extensor radial curto do carpo'],['Membro superior - antebraço','m. extensor radial longo do carpo'],['Membro superior - antebraço','m. braquiorradial'],['Membro superior - antebraço','RETINÁCULO DOS EXTENSORES'],['Membro superior - antebraço','m. pronador redondo'],['Membro superior - antebraço','m. flexor radial do carpo'],['Membro superior - antebraço','m. palmar longo'],['Membro superior - antebraço','m. flexor superficial dos dedos'],['Membro superior - antebraço','m. flexor profundo dos dedos'],['Membro superior - antebraço','m. flexor ulnar do carpo'],['Membro superior - antebraço','m. pronador quadrado'],['Membro superior - antebraço','RETINÁCULO DOS FLEXORES'],
    ['Membro inferior - quadril e coxa anterior','m. psoas maior'],['Membro inferior - quadril e coxa anterior','m. ilíaco'],['Membro inferior - quadril e coxa anterior','iliopsoas'],['Membro inferior - quadril e coxa anterior','m. pectíneo'],['Membro inferior - quadril e coxa anterior','m. adutor curto'],['Membro inferior - quadril e coxa anterior','m. adutor longo'],['Membro inferior - quadril e coxa anterior','m. adutor magno'],['Membro inferior - quadril e coxa anterior','m. grácil'],['Membro inferior - quadril e coxa anterior','m. sartório'],['Membro inferior - quadril e coxa anterior','M. QUADRÍCEPS FEMORAL'],['Membro inferior - quadril e coxa anterior','m. reto femoral'],['Membro inferior - quadril e coxa anterior','m. vasto lateral'],['Membro inferior - quadril e coxa anterior','m. vasto medial'],['Membro inferior - quadril e coxa anterior','m. tensor da fáscia lata'],
    ['Membro inferior - perna anterior/lateral','m. tibial anterior'],['Membro inferior - perna anterior/lateral','m. extensor longo do hálux'],['Membro inferior - perna anterior/lateral','m. extensor longo dos dedos'],['Membro inferior - perna anterior/lateral','m. fibular longo'],['Membro inferior - perna anterior/lateral','m. fibular curto'],['Membro inferior - perna anterior/lateral','m. fibular terceiro'],['Membro inferior - perna anterior/lateral','m. extensor curto dos dedos'],['Membro inferior - perna anterior/lateral','m. extensor curto do hálux'],['Membro inferior - perna anterior/lateral','RETINÁCULOS DOS EXTENSORES superior e inferior'],['Membro inferior - perna anterior/lateral','RETINÁCULO DOS FIBULARES'],
    ['Membro inferior - quadril e coxa posterior','m. glúteo máximo'],['Membro inferior - quadril e coxa posterior','m. glúteo médio'],['Membro inferior - quadril e coxa posterior','m. glúteo mínimo'],['Membro inferior - quadril e coxa posterior','m. piriforme'],['Membro inferior - quadril e coxa posterior','m. gêmeo superior'],['Membro inferior - quadril e coxa posterior','m. gêmeo inferior'],['Membro inferior - quadril e coxa posterior','m. obturador interno'],['Membro inferior - quadril e coxa posterior','m. quadrado femoral'],['Membro inferior - quadril e coxa posterior','m. semitendíneo'],['Membro inferior - quadril e coxa posterior','m. semimembranáceo'],['Membro inferior - quadril e coxa posterior','m. bíceps femoral'],['Membro inferior - quadril e coxa posterior','m. grácil'],
    ['Membro inferior - perna posterior','m. gastrocnêmio - cabeça lateral'],['Membro inferior - perna posterior','m. gastrocnêmio - cabeça medial'],['Membro inferior - perna posterior','m. sóleo'],['Membro inferior - perna posterior','tendão do calcâneo'],['Membro inferior - perna posterior','m. tibial anterior'],['Membro inferior - perna posterior','m. flexor longo dos dedos'],['Membro inferior - perna posterior','m. fibular longo'],['Membro inferior - perna posterior','m. fibular curto'],['Membro inferior - perna posterior','m. fibular terceiro'],
    ['Pescoço','m. esternocleidomastoideo'],['Pescoço','m. esterno-hióideo'],['Pescoço','m. escaleno anterior'],['Pescoço','m. escaleno médio'],['Pescoço','m. escaleno posterior'],
    ['Tórax','m. peitoral maior'],['Tórax','m. peitoral menor'],['Tórax','mm. intercostais externos'],['Tórax','mm. intercostais internos'],['Tórax','m. serrátil anterior'],['Tórax','m. diafragma'],
    ['Dorso e cintura escapular','m. trapézio'],['Dorso e cintura escapular','m. latíssimo do dorso'],['Dorso e cintura escapular','aponeurose toracolombar'],['Dorso e cintura escapular','m. rombóide menor'],['Dorso e cintura escapular','m. rombóide maior'],['Dorso e cintura escapular','m. levantador da escápula'],['Dorso e cintura escapular','m. supraespinal'],['Dorso e cintura escapular','m. infraespinal'],['Dorso e cintura escapular','m. redondo menor'],['Dorso e cintura escapular','m. redondo maior'],['Dorso e cintura escapular','m. deltóide'],['Dorso e cintura escapular','m. ileocostal - cervical, torácico e lombar'],['Dorso e cintura escapular','m. dorsal longo - cabeça, pescoço e tórax'],['Dorso e cintura escapular','m. espinal - cabeça, pescoço e tórax'],['Dorso e cintura escapular','m. serrátil posterior inferior'],['Dorso e cintura escapular','EPIMÍSIO'],
    ['Abdome','m. reto do abdome'],['Abdome','intersecções tendíneas do músculo reto do abdome'],['Abdome','m. oblíquo externo do abdome'],['Abdome','m. oblíquo interno do abdome'],['Abdome','m. transverso do abdome']
  ].map((x,i)=>({id:'mus-'+(i+1),roteiro:'Sistema Muscular',grupo:x[0],numero:i+1,nome:x[1]}))
];
const DB_NAME='roteirosAnatomiaDB', STORE='registros'; let db;
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error);});}
function getReg(id){return new Promise(res=>{const tx=db.transaction(STORE,'readonly');const rq=tx.objectStore(STORE).get(id);rq.onsuccess=()=>res(rq.result||{id,notes:'',photos:[],files:[]});});}
function putReg(reg){return new Promise(res=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(reg);tx.oncomplete=res;});}
function readAsDataURL(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(file);});}
async function buildCard(item){const tpl=document.getElementById('cardTemplate');const card=tpl.content.cloneNode(true).querySelector('.card');card.dataset.id=item.id;card.querySelector('h2').textContent=`${item.numero}. ${item.nome}`;card.querySelector('.roteiro').textContent=item.roteiro;card.querySelector('.grupo').textContent=item.grupo;card.querySelector('.meta').textContent=`Roteiro: ${item.roteiro} • Grupo: ${item.grupo}`;const reg=await getReg(item.id);const notes=card.querySelector('.notes');notes.value=reg.notes||'';notes.addEventListener('input',async()=>{const r=await getReg(item.id);r.notes=notes.value;await putReg(r);updateSummary();});const render=async()=>{const r=await getReg(item.id);const prev=card.querySelector('.preview');prev.innerHTML='';(r.photos||[]).forEach(src=>{const img=new Image();img.src=src;prev.appendChild(img)});const fl=card.querySelector('.file-list');fl.innerHTML='';(r.files||[]).forEach(f=>{const d=document.createElement('div');d.textContent=`Arquivo: ${f.name}`;fl.appendChild(d)});};card.querySelector('.photoInput').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;const r=await getReg(item.id);r.photos=r.photos||[];for(const f of files) r.photos.push(await readAsDataURL(f));await putReg(r);await render();updateSummary();e.target.value='';});card.querySelector('.fileInput').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;const r=await getReg(item.id);r.files=r.files||[];for(const f of files) r.files.push({name:f.name,type:f.type,size:f.size,date:new Date().toLocaleString('pt-BR')});await putReg(r);await render();updateSummary();e.target.value='';});await render();return card;}
async function render(){const q=document.getElementById('search').value.toLowerCase();const rf=document.getElementById('roteiroFilter').value;const sf=document.getElementById('statusFilter').value;const wrap=document.getElementById('cards');wrap.innerHTML='';for(const item of itens){const reg=await getReg(item.id);const matchText=[item.nome,item.grupo,item.roteiro].join(' ').toLowerCase().includes(q);const matchRot=rf==='todos'||item.roteiro===rf;const hasPhoto=(reg.photos||[]).length>0, hasFile=(reg.files||[]).length>0;const matchStatus=sf==='todos'||(sf==='com-foto'&&hasPhoto)||(sf==='com-arquivo'&&hasFile)||(sf==='pendente'&&!hasPhoto&&!hasFile&&!reg.notes);if(matchText&&matchRot&&matchStatus) wrap.appendChild(await buildCard(item));}updateSummary();}
async function updateSummary(){let fotos=0, arquivos=0, notas=0;for(const item of itens){const r=await getReg(item.id);if((r.photos||[]).length)fotos++;if((r.files||[]).length)arquivos++;if(r.notes)notas++;}document.getElementById('summary').innerHTML=`<div class="summary-card"><strong>${itens.length}</strong><span>estruturas</span></div><div class="summary-card"><strong>${fotos}</strong><span>com foto</span></div><div class="summary-card"><strong>${arquivos}</strong><span>com arquivo</span></div><div class="summary-card"><strong>${notas}</strong><span>com anotações</span></div>`;}
async function init(){await openDB();await render();document.getElementById('search').oninput=render;document.getElementById('roteiroFilter').onchange=render;document.getElementById('statusFilter').onchange=render;document.getElementById('exportBtn').onclick=()=>window.print();document.getElementById('clearBtn').onclick=async()=>{if(confirm('Apagar todas as fotos, arquivos e anotações salvas neste app?')){await new Promise(res=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=res});render();}};if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;const b=document.getElementById('installBtn');b.classList.remove('hidden');b.onclick=async()=>{await deferred.prompt();b.classList.add('hidden');};});}
init();
